llms: local, ollama

local:
  model_path: data/zephyr-7b-beta.Q4_K_M.gguf
  max_new_tokens: 1536
  ctx_len: 3072
  gpu_layers: -1
  temp: 0.65

ollama: 
  model: dolphin-phi:2.7b-v2.6-q6_K
  max_new_tokens: 1024
  ctx_len: 2048
  temp: 0.65