llms: local, ollama

local:
  model_path: data/phi-2-super.Q5_K_S.gguf
  max_new_tokens: 1536
  ctx_len: 3072
  gpu_layers: -1
  temp: 0.65

fireworks:
  model: accounts/fireworks/models/mistral-7b-instruct-v0p2
  max_tokens: 2560
  temp: 0.65

ollama: 
  model: dolphin-phi:2.7b-v2.6-q6_K
  max_new_tokens: 1124
  ctx_len: 2536
  temp: 0.5
  num_gpu:
  format:
  headers:
  mirostat: 1

ollama2: 
  model: mithun/magicoder:6.7B-S-DS-Q4_K_M 
  max_new_tokens: 2048
  ctx_len: 8192
  temp: 0.65
  num_gpu:
  format: json
  headers:
  mirostat:

openailike:
  model: deepseek-coder
  base_url: https://api.deepseek.com/v1
  max_tokens: 2048
  temp: 0.65